### ISSUE TITLE
[CONTENT] Stress on the front page that Hedy leads up to Python

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#1623]
We don't explicitly name that now, could be explained better.

**Comment by curtcox** [comment]
I really enjoyed the [StrangeLoop video](https://www.youtube.com/watch?v=fmF7HpU_-9k) which led me here.

I came looking to see if there was an easy way to install Hedy locally, so that any programs written could be run locally.
If one could install Hedy via the standard package managers like brew and apt then more home automation and robotics
examples could be developed that work autonomously and offline.

This might be a case where adding features that appeal to professional programmers grows the community in a way
that makes it more attractive to everyone. 

Perhaps "export as Python" or "open as Python in replit" would be better and easier ways of accomplishing something 
similar to what I'm asking for.

**Comment by Felienne** [comment]
Hi @curtcox!

Welcome to Hedy :) While I have no objections at all to someone eases local running, I do not think this is in the scope of what we are trying to do at the moment, since we mainly target schools. But absolutely feel free to make some steps towards this, you are probably right it might attrackt programmers!

**Comment by Felienne** [comment]
After consideration, I think we can close this for the frontpage. It is clear on the GitHub, where it matters, and for teachers it doesn't really have meaning. It would be nice to add it to the teacher materials, in a new chapter "after Hedy". I will make a new issue for that.
