### ISSUE TITLE
[BUG] Error when using `vraag` as a variable in level 3 (language Dutch, keywords English)

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#3274]
When I try to run this code in level 3 I get an error 
```
vraaga is vind je honden aardig, doe jij teveel gamen, je ging op pad
print vraaga at random
```

the error is:

`Dat was goede code hoor, maar niet op het goede level. Je schreef een ask voor level 1. Tip: Vanaf level 2 hoort ask met een variabele ervoor. Bijv: naam is ask Hoe heet jij?`

I think there is some translation problem because the variable name `vraaga` is part of a Dutch command `vraag` (ask). I use Dutch as the main language and English as the keyword language. 

![image](https://user-images.githubusercontent.com/10562903/189676651-a4941618-9f9d-4851-a77c-c6c6a5cf47df.png)

**Comment by Felienne** [comment]
Interesting.....! I will tke a look @OnnoEbbens!

**Comment by Felienne** [comment]
I understand the problem @OnnoEbbens but it will not be very easy to fix because we use this error system, to catch other potential and common errors.

For now it is best to teach them not use something starting with `vraag` as variable name in this case. `vraga` ot `vra` do work (yeah not so elegant I know!!!)
