### ISSUE TITLE
[CHORE] Run code formatter on PRs

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3377]
We can probably do that this way: 

https://github.com/marketplace/actions/autopep8 (earlier version of this issue suggested black but I think PEP8 will do just fine!)

**Comment by Felienne** [comment]
In principle, I think this is a great first issue since it does not require knowledge of our code base and will be easy, given that you have done such a thing before!

**Comment by mennoliefstingh** [comment]
All right never mind, I've done some further tests and even after formatting the code base with both autopep8 and black, my linter (flake8) still reports a lot of warnings and non pep-compliancy.  Autopep8 is a lot less strict and e.g. doesn't split long lists over multiple lines like Black does, meaning some lines remain extremely long. Black makes the code look a lot better in my opinion, but still doesn't solve a lot of issues like the following:

- Unused imports
- Unused local variables
- Lines that are too long and cannot be split by black/autopep8, usually because they're comments
- 'Bare' exceptions (except: instead of except ValueError: for example)

Specifically in the tests:
- Lambda expressions that should be regular functions (def:)
- f-strings without placeholders in the tests (so f"blablabla" instead of "blablabla",  maybe there's a reason for this)

Don't shoot the messenger as these are flake8's words and not mine, but making the code base pep-compliant and subsequently enforcing style through git hooks would require a lot more work than just running a formatter and writing a yaml file. This basically leaves two options: either reformatting the repo with Black, run flake8 and manually fix non-compliant code or just saying 'never mind' and stick with the codebase as it is now.

**Comment by bspans** [comment]
Was wondering if this issue is still a problem, or if I can help with this. In the afore mentioned issue #3410 It is said that there should be two pull requests, but i'm not sure on what needs to be done at this moment.

**Comment by craigmulligan** [comment]
Hey :wave: 

I have a little experience using both black & flake8. While black is PEP8 compliant it is conservative in what it formats and won't change anything that could break the program, which means it won't automatically fix things like unused imports. So you'll likely have to use both a linter and a formatter to cover the issues mentioned in this thread. 

The two tools work fairly well together, black has some documentation on that [here](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8).

* I had a quick look at the repo a first pass of flake8 there are *4479* PEP8 violations.
* After running black there were *825* PEP8 violations left. 
* The last 825 violations are probably non-formatting related PEP8 issues or things that black is conservatively ignoring, like long lines in doc strings (black ignores line-length in doc strings because there is sometimes structured data in there are you'd need to parse the docstring to split the line correctly.) 

To tackle the remaining outstanding *825* issues you have a few options. 

1. Just fix them manually in a single batch. 
2. Use flake8 --diff option and only run it on the diff in each PR. I've never done this before but should work fine? 
3. Automatically add `# noqa <ERROR-NO.>` to all issues. [See this script](https://gist.github.com/AlexRiina/d8dfd39d2c6c4b121c8776070a2272dc)

I'd probably go for a mix of 1 + 3, fixing easy issues and ignoring ones that require any real logic changes.

Once the code is in a consistent state and is PEP8 compliant the only thing left is to add a black check to the ci. Something like `python -m black . --check`.

Happy to put this together in a PR if everyone is happy with the approach.

**Comment by Felienne** [comment]
> Hey 👋
> 
> I have a little experience using both black & flake8. While black is PEP8 compliant it is conservative in what it formats and won't change anything that could break the program, which means it won't automatically fix things like unused imports. So you'll likely have to use both a linter and a formatter to cover the issues mentioned in this thread.
> 
> The two tools work fairly well together, black has some documentation on that [here](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8).
> 
> * I had a quick look at the repo a first pass of flake8 there are _4479_ PEP8 violations.
> * After running black there were _825_ PEP8 violations left.
> * The last 825 violations are probably non-formatting related PEP8 issues or things that black is conservatively ignoring, like long lines in doc strings (black ignores line-length in doc strings because there is sometimes structured data in there are you'd need to parse the docstring to split the line correctly.)
> 
> To tackle the remaining outstanding _825_ issues you have a few options.
> 
> 1. Just fix them manually in a single batch.
> 2. Use flake8 --diff option and only run it on the diff in each PR. I've never done this before but should work fine?
> 3. Automatically add `# noqa <ERROR-NO.>` to all issues. [See this script](https://gist.github.com/AlexRiina/d8dfd39d2c6c4b121c8776070a2272dc)
> 
> I'd probably go for a mix of 1 + 3, fixing easy issues and ignoring ones that require any real logic changes.
> 
> Once the code is in a consistent state and is PEP8 compliant the only thing left is to add a black check to the ci. Something like `python -m black . --check`.
> 
> Happy to put this together in a PR if everyone is happy with the approach.

Thanks for the ping @craigmulligan! @mennoliefstingh and @jpelay are working on this, if you want to help out it would be best to hop on our Discord and chat with them about the status there: https://discord.gg/GzfaTWc6

**Comment by mennoliefstingh** [comment]
Copying my discord reply here:

Menno — gisteren om 10:27
Hi Craig, welcome to the discord! We're actually doing almost exactly that haha, @jpelay and I have been manually fixing the code styling and we were discussing what kind of CI to introduce (see above). We chose to use autopep8 and isort instead of black. I've used black a lot professionally and it's been part of most if not all of our ci/cd pipelines, but we'd like to keep the project as accessible as possible for people who don't write Python professionally. Autopep8 strictly fixes pep8 compliance and doesn't go beyond that like black does. 

Anyway, once we merge PR 3675 and the one Jesús has been working on (not sure if we've merged that already) the code base should be pep8-compliant, so the next step is making sure it stays that way. We have a pre-commit hook in the repository, but were discussing a server-side solution in this thread. I guess we're (or I am) leaning towards running isort and autopep8 on changes. I think adding noqa to lines that aren't fixed by autopep8 is a really good idea.
