### ISSUE TITLE
[UI idea] Profile icon shifts when new message

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#3428]
**Idea incl level**
The navigation bar profile icon shifts and makes the UI a mess when we have a pending message:
<img width="1537" alt="Schermafbeelding 2022-10-18 om 00 15 45" src="https://user-images.githubusercontent.com/38155424/196294311-cd8e99a8-7c6c-42ae-b17c-0376fd282c80.png">

**Comment by TiBiBa** [comment]
To add on this: It might be nice to have the message indicator placed for the username when on a right-to-left language.

**Comment by Lz-01** [comment]
please add this issue to me

**Comment by jtwaleson** [comment]
This was fixed in b8c1d951ac0e0082bf4916cf4136b8b9c846794c in January 2023. Issue can be closed.

Screenshot from current main branch shows no wrapping on that line even with very long user names:

![Screenshot from 2023-09-24 13-29-45](https://github.com/hedyorg/hedy/assets/1298565/0f8502dd-8440-4491-a9ab-7ec09578ad81)
