### ISSUE TITLE
[HIGHLIGHTING] do not highlight multiple is-es

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3452]
Currently `is` is highlighted in list elements:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/1003685/196642005-b6b77433-f415-46fc-9daf-670c184afaaa.png">

Level 10
```
rappers is Brainpower is ge, Ronnie Flex is ge, Sticks is ge
score is stoord, tikt, itengeblaat
for rapper in rappers
  print rapper score at random
        
```

Could we highlight the list elements (also if they are not quoted in levels below 12) as purple in all cases? That will reflect a bit more what is happening.

**Comment by thjazi39** [comment]
Ok, I'll think about how to do it simply, without it being a problem when nesting commands in the list assignment (even if I have the impression that you can only put text in a list, you can't, for example, do: `list2 is list1 at random, list1 at random`)

And on the other hand, the "is" is also used in tests, and in simple value assignments.

As soon as I have some free time I try to develop a regex to select only this case.

Then I can decide whether to highlight the list elements in purple, or leave them blank. Because there is also the case of lists of numbers, which can really be used as numbers, with mathematical operations, and maybe highlighting in purple can be misleading)

**Comment by thjazi39** [comment]
A example of code with different variation of is : 
```list is 1,2,3,4,5,6,7,8,9,10,11
v1 is list at random
v2 is list at random
print v1 + v2
print v1 * v2
print "Find v1 and v2 !"

vR is ask "gives one of the two !"
ok is 0
if vR is v1
    ok is 1
if vR is v2
    ok is 1

if ok is 1
    print "Yess!!!"
else
    print "No.."

print "v1 is " v1
print "v2 is " v2
```
![image](https://user-images.githubusercontent.com/48509466/196769212-31ccb5b0-0d22-4a94-9692-bb6fc359d243.png)

**Comment by Felienne** [comment]
> As soon as I have some free time I try to develop a regex to select only this case.

Thank you!!

**Comment by Felienne** [comment]
And yeah I agree it is tricky! But it would be nice to try!

**Comment by Felienne** [comment]
Fixed with the new editor!
