### ISSUE TITLE
[BUG] 'str' object not callable

### ISSUE THREAD

**Issue by sjensen19** [hedyorg/hedy#3454]
**Describe the bug**
I don't exactly know what the bug is, but when running the following program in level 11, the program crashes after the 'ask' statement with an error 'str object not callable'. 

**Paste the Hedy code & level**
![image](https://user-images.githubusercontent.com/55716630/196659089-8fd5e60f-c142-473a-8b3c-ef8a823520a6.png)

**Expected behavior**
This program should run fine without any issues.

**Comment by JonathanMurray** [comment]
I took a look at this, and I think the issue comes from the variable being named `input`. The error seems to happen right when the "Jump?" question is about to appear for the second time.

From what I can understand, Hedy parses the user-provided code into the following (Python?) code:
```
score = '0'
jump = '0'
jumpTime = ['1', '2', '3', '4', '5']
step = 1 if int(0) < int(100) else -1
for i in range(int(0), int(100) + step, step):
  if jump in jumpTime:
    jump = int(jump) - int(1)
    print(f'Is jumping')
  else:
    input = input(f'Jump?')
    if convert_numerals('Latin', input) == convert_numerals('Latin', 'w'):
      jump = '5'
  time.sleep(0.1)
```
(It's the response that my browser gets from a `/parse` call.)

If this executed as Python code, it makes sense that the second invocation of `input = input(f'Jump?')` would fail, as `input` is now a `str` rather than a function that can be invoked.

Indeed, if you change the name of the variable from `input` to something else, it suddenly works!

**Comment by JonathanMurray** [comment]
(Assuming I understood the root cause correctly)
As for fixing the issue, there could be reasons against it that I'm unaware of, but perhaps the code-translator could "mangle" / modify all supplied variable names to ensure that they don't clash with Python key-words?
