### ISSUE TITLE
[UI idea] Improve UX around the guttter

### ISSUE THREAD

**Issue by nycdotnet** [hedyorg/hedy#3508]
**Idea for all levels**
I was showing Hedy to my 7 year old who has very limited computer experience beyond video games.  I noticed that he had particular trouble setting the cursor to the beginning of a line with the mouse in the Hedy interface.  He would be more likely to do one of these three things with the mouse rather than get the cursor aligned at the start of the line:
  * Click too far to the left and "comment out" the line with the 🤫 feature
  * Click too far to the left and select the line rather than position the cursor
  * Because he needed to be careful not to click on the gutter area, sometimes he would click to the right of the midpoint of the first character so the cursor was at position 2 instead of 1.  (for example if the line was `print x` it would be between the `p` and `r`).

I suggest one or all of the following which I can attempt to implement:
1. The active area for the "comment out" 🤫 feature should be far more to the left.
2. The gutter should not select the line on a single click - possibly on a double-click.  It should just place the cursor at position 1.

**Additional context**
This is for a brand new computer user so may not be relevant, but could also potentially improve accessibility.  For RTL languages, I assume this would need to be reversed - I haven't checked.

**Comment by Felienne** [comment]
Hi @jpelay!

Here too, let's check if these issues are solved with CodeMirror. If not we can open separate ones for each and pick them up as we improve

**Comment by jpelay** [comment]
> Hi @jpelay!
> 
> Here too, let's check if these issues are solved with CodeMirror. If not we can open separate ones for each and pick them up as we improve

Hi @Felienne! I have good news about this issue too:

1. Clicking the beginning of the line does not select the whole line.
2. Clicking on the line gutter does not do anything, since the breakpoints gutter have now been moved to the left. Now the gutter looks like this:

![image](https://github.com/hedyorg/hedy/assets/45865185/6584a30e-3246-421a-afcc-f5d9252eab2e)

It has a space to the left that is clickable and the user can place a breakpoint there (I still need to implement that the line needs to be strikethrough).

I think this implementation follows more closely the way breakpoints work in professional editors, like Visual Studio Code, where clicking in the line gutter does not do anything, but clicking in a gutter to the left does add a breakpoint:

![image](https://github.com/hedyorg/hedy/assets/45865185/b40be3fb-b128-44c2-9139-c4c99dc1be59)

**Comment by jpelay** [comment]
> Great! So I gather we can close this issue?

Pretty sure we can!
