### ISSUE TITLE
[CONTENT] DESIGN.MD

### ISSUE THREAD

**Issue by LeslieMurphy** [hedyorg/hedy#3517]
**Describe the issue**
The overall design should explain that the server side does the transpiling into Python, then Python runs in the browser complement of Skulpt.

**Expected text**

DESIGN.MD

```
1. Hedy code is sent via HTTP POST from the browser to the server
2. The server parses the student's code based on the relevant grammar, creating an AST. This is done using the open source Lark parser.
3. Validity of the code is checked with the IsValid() function
4. If the code is valid, it is transformed into Python with the relevant function.
5. The generated Python code is returned to the browser as a response from the POST
6. The browser interprets and runs the Python code using [Skulpt](http://skulpt.org/)

The logic for steps 2-5 all resides in hedy.py.
```

<img width="499" alt="image" src="https://user-images.githubusercontent.com/4464416/198721796-6be4abb0-5ab1-4a3b-9998-b3eb7ec53bfb.png">

**Comment by Felienne** [comment]
@LeslieMurphy thanks for this issue but I want to point out that, as per our README, the phrasing of this issue does not really fit the way we interact with each other in this project. Please phrase issues constructively: "Would it be clearer if...?" "Could we add ....?" rather than "You should".

In my opinion, these type of changes are a trade-off. While your suggestion adds more info, yes, more information can also be overwhelming for newcomers! For example I do not think that the information about the POST is useful to give a broad overview of what Hedy is. 

I totally agree our documentation could be improved, but my proposed path forward is to do so by having a clear goal and audience in mind and organising all documents accordingly. We will discuss this in the next Hedy contributors meeting.

**Comment by LeslieMurphy** [comment]
Thanks. That makes sense.  I should have suggested "Would it be clearer if
the README explained the roles of the server side and client side
components of Hedy" and left the rest to your team!

**Comment by Felienne** [comment]
Thanks for understanding!! In the end it did help us understand where we can improve things!
