### ISSUE TITLE
[CONTENT] Use {} everywhere around keywords

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3537]
As pointed out in #3514 some languages do not yet use {} around keywords for legacy reasons:

https://github.com/hedyorg/hedy/blob/1dfa0d9e11dee5646fb79c7d7960ad27be504ca9/content/adventures/de.yaml#L1402

Would be great if someone could fix that with a bit of prepping (here or in Weblate, both is fine by me!)

**Comment by ana3999** [comment]
Hello!
My partner and I are looking to contribute to Hedy and we thought that this issue might be a good first issue to tackle to familiarize us with the codebase! Would it be possible for us to claim this issue? 
Thank you so much!

**Comment by Felienne** [comment]
Absolutely, we'd be very happy if someone picks this up. It would be nice
if you could do it in small steps (for example in a few languages at a
time, or for a few levels at a time) to minimize conflicts with other
translators in Weblate (our translation system)

Let us know if you need any help (either here or in Discord!)

**Comment by ana3999** [comment]
Thank you so much Felienne! 
We are extremely excited to start working on this task! I have reached out to you on Discord about a couple questions we had about this issue

**Comment by jpelay** [comment]
> Hi @jpelay!!
> 
> I know you were working on this today while translating, can we close it, are you convinced you caught them all or do we need to keep it open so we don't forget to check later?

The issue I was working on was different I think! Instead of languages not having the {} around keywords, it was caused by {} being around keywords in normal text! For example (not real, just an example):

'You can {ask} the user for clarification'
'{if} the user says yes, print hey, {else}...'

@TiBiBa said that this was caused by an automatic script and wasn't intetional. What I can do is review it in English and remove the {} where they don't make sense. But I think that's a separate issue from this.
