### ISSUE TITLE
[TESTING] Create front-end test for the admin users overview page

### ISSUE THREAD

**Issue by hanna1231** [hedyorg/hedy#3705]
Create front-end tests for all features on the `/admin/users` page:

- 'Return to admin page' button
- 'View all users' button
- Visible attributes - checking on/off attributes
- Filtering options - filtering on created/last login/username/etc..

**Comment by JimmyOei** [comment]
Can be improved:
- use the page names in the cypress config to check of you are on the right page, because checking if the page is equal to the current page name requires a lot of work to change every bit of code when it is decide to change a page name. If this were just a reference to what the current page name is in the config file then we only have to change this instance when the page is changed in the future.
- there can also be some more modularity in the tests by creating id's in the html, instead of doing for example `'.fle > .green-btn'`.
- Maybe create a goToAdminUserOverviewPage function as a tool in ``nav.js``
