### ISSUE TITLE
[LANGUAGE idea] Add new exception for `at random` used on level 16

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#3800]
**Language idea incl level**

I really don't know if this error is at all common, but I've noticed that when a user tries to access a list with `at random` on level 16, it throws an ugly parse error. Maybe we can add that rule as an error on level 16 and throw a nice error message instead?

**Additional context**

This should throw a nice error message:
![image](https://user-images.githubusercontent.com/45865185/206235973-ac822dcb-fc81-475f-88d7-ab95b3a17173.png)

**Comment by heemlanden-bch** [comment]
This would be nice indeed, I also have some students that are running into this.

Perhaps a simpler fix could be to add a line to the introduction of Level 16 that states something like: Also, from now on you can write `fruit[random]` instead of `fruit at random` to get a random item from the `fruit` list?

**Comment by boryanagoncharenko** [comment]
It seems that both the better error message and the content change are already there:
<img width="748" alt="Screenshot 2024-04-04 at 16 07 38" src="https://github.com/hedyorg/hedy/assets/3010723/812ef0d6-1431-4de4-8597-6f2935b8270c">
