### ISSUE TITLE
💻 Upload of a CSV file to create student accounts for a class

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3936]
### Discussed in https://github.com/hedyorg/hedy/discussions/3933

<div type='discussions-op-text'>

<sup>Originally posted by **stevecopley** January 13, 2023</sup>
When I'm using Scratch with a class, to avoid too much faffing about, I usually create the student account ahead of the first lesson. Scratch has the ability to upload a **CSV file** with a list of usernames/passwords to mass-create the accounts and link them to the current class. Something similar for Hedy would be great.

(Would be good to have a downloadable template CSV file with a couple of examples in to give teachers clear guidance as to the fields/formats you required.)

</div>

**Comment by boryanagoncharenko** [comment]
During the last contributors meeting we noted the following things:
- [ ] To support pasting from Excel, we should subscribe to the paste event and politely replace all \t tabs with semicolons. See this in the demo.
- [ ] When the checkbox with ‘Auto generate password’ is unchecked, its text should change to ‘Provide your own passwords’. See this in the demo.
- [ ] Instead of downloading a file, we could display the created accounts in the browser and let the teacher print them. The best solution I was able to think of is to hide the input form and dynamically fill a table with the usernames and passwords. A print button above the table allows the teacher to print only the table (and not the whole page). See this in the demo.
- [ ] Show to the user that the website is loading (since creating student accounts is a long operation and they will get confused if there is no clear indication). I have a very rough version of a spinner which needs to be made visually appealing. But the base is there. See the demo.
- [ ] Refurbish the suffix modal. The word 'suffix' is not clear enough, the dialogue is too busy, and it is not quite clear what it will do. I think, it is better just tell the user that these accounts exist and they need to change them. @AnneliesVlaar @MarleenGilsing Do you agree or may be you have any suggestions?
- [ ] Investigate why it takes so long. **Locally** it takes 45 seconds to generate 30 student accounts. It is a good idea to check why before we deploy. @jpelay said he is interested in investigating.

Am I missing anything?

This is the demo. Please let me know whether you like it!

https://github.com/user-attachments/assets/fa88b965-a6d4-4dcb-af1a-a6900c833c22
