### ISSUE TITLE
[BUG] confusing error message in level 4 for unmatched quotes

### ISSUE THREAD

**Issue by vgrigoriu** [hedyorg/hedy#3967]
**Describe the bug**

In level 4 if you miss a closing quote:

```
print 'Hello world
```

you get a helpful error that says:

```
Be careful. If you `ask` or `print` something, the text should start and finish with a quotation mark.
You forgot that for the text 'Hello world.
```

However, if the unterminated string contains a comma, then the error message is confusing:

```
The code you entered is not valid Hedy code. There is a mistake on line 1, at position 13.
You typed a comma, but that is not allowed.
```

**Paste the Hedy code & level**

Level 4:

```
print 'Hello, world
```

(https://hedycode.com/hedy/6978271c818f42d9b6021f670ee47e2b/view)

It seems to me that the error message should be the same as in the first case, where there's no comma. If you agree, I'm willing to try to fix this. Or this there a fundamental reason why we can't handle the two cases the same?

**Comment by vgrigoriu** [comment]
I wonder if this is related to https://github.com/hedyorg/hedy/issues/3381?

**Comment by Felienne** [comment]
HI @vgrigoriu!  

Yes it is surely related to `,` being a list separator. If you are interested in taking a stab at this, go ahead! For us improving error messages it on the road map at this moment. If you want to discuss this more, do hop over to Discord or join a Tuesday meeting!

**Comment by schneems** [comment]
I think it's important that error messages that give specific information have a high degree of confidence. It's really annoying to get "restart your browser to solve this problem" after you've already tried restarting it a dozen times. One technique that I used in Ruby 3.2's syntax suggestion feature (https://github.com/ruby/syntax_suggest) is to delete and re-parse code.

I hear you're not in a position to immediately work on this. Here's some high level thoughts. I'm curious if you think one might be more-or-less viable than others.

## Generalized fix for single character detected syntax problems

We could perhaps write a generalized logic rule for error messages that single out a specific character. If we can delete the character and re-parse to create a valid document, then we have a high degree of confidence it's causing the problem, otherwise something else might be going on.

For example:

```
print "Hello world", 
```

Would be fixed by removing the comma, but:

```
print "Hello world,
```

Would still be a syntax error with the comma removed. We could use that information to deliver better error messages.

## Make existing error message more precise in wording 

Barring a better fix, we could improve the message to be more technically accurate. This message doesn't make sense by itself:

```
You typed a comma, but that is not allowed.
```

Students know that commas are allowed because they're used in other contexts. Commas are allowed inside strings or lists, but not outside of them. I'm unfamiliar with the codepath that produces this specific message, but maybe we could update it so something more technically accurate. For example:

```
You typed a comma here, but hedy cannot figure out what you were trying to do. 
```

## A help suggestion to guide to the next error message

Rust is great with suggestions. We could add them to the case of a single invalid character found:

```
You typed a comma here, but hedy cannot figure out what you were trying to do. 

Help: Try removing this comma and re-running your program to see if it fixes the error or changes the message.
```

If they got this, they would delete the comma and re-run and see a different (better) error message:

```
Be careful. If you `ask` or `print` something, the text should start and finish with a quotation mark.
Hint: Try adding a quotation mark at the end of the text 'Hello world. 
         Then re-run your program to see if it fixes the error or changes the message.
```

FWIW I love the "fix the error or change the message" mantra as a programming philosophy as it turns failure states into more of a learning/growth opportunity.

## A social solution

A possible solution that wouldn't involve needing to modify error messages would be: Introduce exercises in hedy that intentionally give students error messages and walk them through fixing them. Ask them socratic method questions about why the computer might be giving you that "weird" output with hints. #4043 could possibly help here if it's not a good fit for the existing hedy interface.

It would actually be really nice to have each section contain some some working and non-working examples of the syntax.

I'm imagining something like:

- Teacher shows:

```
print 'Hello world
```

Teacher asks: What do you think happens when you run this code?
Students: ...
Teacher: Let's try it.

```
Be careful. If you `ask` or `print` something, the text should start and finish with a quotation mark.
You forgot that for the text 'Hello world.
```

Teacher: That's not what we expected, what went wrong?
Students:
Teacher: Here's how we fix it...

Teacher: What about this code:

```
animals is dog cat kangaroo
add penguin to animals
print animals at random
```
Student: ...
Teacher: Here's the output:

```
You cannot use add to with animals because it is text. Try changing animals to a list.
```

Teacher: Why does it think that animals is a string? Did we forget something? How do we fix it?

Then:

Teacher: How about this code:

```
print 'Hello, world
```

Teacher: It says there's a problem with the comma. What if we remove it, what do you think will happen, do you think that will fix the program? No? Well...let's try anyway to see what happens.
