### ISSUE TITLE
Improve handling of server responses and response codes

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4029]
An old PR (#3836) from @TiBiBa had the following objectives in mind

- [ ] > * Replace all jsonify() returns to make_response() with the corresponding response code
- [ ]  > * Remove all hard-coded response messages, even when not likely to be returned to user
-> #5558 
- [x] > * When return an empty succes, use 204 instead of 200 https://github.com/hedyorg/hedy/pull/5455
- [x] > * Improving the other error codes is handled in a separate issue https://github.com/hedyorg/hedy/issues/3634

That PR was closed because it was getting old and further refactors changed those files and made continuing working on that branch unfeasible. That's why I'm opening this issue to work on this later on!

**Comment by Annelein** [comment]
> * [ ]   > * Remove all hard-coded response messages, even when not likely to be returned to user

@jpelay does this mean change all of these, into `return make_response(gettext("request_invalid"), 400)` ?


```
if not body:
        return "body must be an object", 400
if 'code' not in body:
        return "body.code must be a string", 400
if 'level' not in body:
        return "body.level must be a string", 400
if 'adventure_name' in body and not isinstance(body['adventure_name'], str):
        return "if present, body.adventure_name must be a string", 400
if 'is_debug' not in body:
        return "body.is_debug must be a boolean", 400
if 'raw' not in body:
        return "body.raw is missing", 400
```

**Comment by Annelein** [comment]
@jpelay and should `return gettext('image_invalid'), 400` be changed to `return make_response(gettext('image_invalid'), 400)` ?

**Comment by jpelay** [comment]
> @jpelay and should `return gettext('image_invalid'), 400` be changed to `return make_response(gettext('image_invalid'), 400)` ?

Yes to both of your questions!

**Comment by rix0rrr** [comment]
> * Remove all hard-coded response messages, even when not likely to be returned to user

I don't have a ball in this game, but consider the following:

Every string you make translatable like this is a string that feels like an obligation to a translator to translate, if they want "100%".

If you're going to make error strings that are only shown when the frontend programmer has made a mistake against the backend contract, then you are making volunteer Arabic or Thai translators spend a lot of time translating strings that will only ever be seen by *you* in English, or perhaps Dutch.

So the question is, what is the benefit the project gets from changing this code? Consistency is the only one I can think of: now you don't have to think anymore which errors get surfaced to users and which don't. Consider what you're paying to get that, and whether it's worth it.

If you're going to go through with this, please strongly consider researching whether it's possible to add tags to translatable strings, and adding a tag like `no-need-to-translate-kthxbai` to the strings, so translators have at least a fighting chance ignoring strings that would be wasted work anyway.

**Comment by Annelein** [comment]
@rix0rrr I agree. I think translating errors messages which will never be seen by the user, is completely useless. So in #5558 I change all hard coded error messages to `return make_response(gettext("request_invalid"), 400)` .

Meaning for example these specific error messages are removed:
```
if not body:
        return "body must be an object", 400
if 'code' not in body:
        return "body.code must be a string", 400
```

I guess it's not ideal and more debugging will be needed in case of an error. But it would be consistent? Or do you think we should discuss in the meeting, wether we even want this?

**Comment by rix0rrr** [comment]
Oh I see! I guess I didn't read closely enough, I just went off the title of the ticket. 🤪 Sorry!

Looks like in the triangle of trade-offs, you went into the bottom right corner:

![image](https://github.com/hedyorg/hedy/assets/524162/d4ee354c-d4e4-463b-8ab0-45cc52dfbed2)

I don't want to second-guess your decision, if that's what you decided to do. Everybody weighs these factors differently.

I personally value human effort higher than code consistency (😈), but I've been doing this job for a long time and I have no problems reading through and working with messy code. If you are fielding a lot of questions on why things are different in different places, or get a lot of people copy/pasting the wrong patterns because they don't understand why things are different and forget to ask, or are just personally annoyed with the state of the code base, I can totally understand why you might weigh the trade-offs differently!

**Comment by Annelein** [comment]
> Oh I see! I guess I didn't read closely enough, I just went off the title of the ticket. 🤪 Sorry!
> 

No worries! You are making some very good points :)

> Looks like in the triangle of trade-offs, you went into the bottom right corner:
> 
Yes I did indeed haha, we just discussed in the meeting, everyone agrees to go for consistency rather than easier debugging. Jesus also mentioned to rarely stumble upon hard coded response messages while debugging.
> 
> I don't want to second-guess your decision, if that's what you decided to do. Everybody weighs these factors differently.
> 
> I personally value human effort higher than code consistency (😈)

Interesting!! Haha, thanks for your input and thoughts. Looking at the code base, I think the project can use a bit more consistency for the amount of contributors it has. Otherwise I would have agreed with you!! 😉

**Comment by rix0rrr** [comment]
Sounds good, sorry for inserting myself into a conversation I didn’t need to be a part of 😬👌

**Comment by Annelein** [comment]
@rix0rrr nooo, thank you for getting involved and pointing out useful comments :))
