### ISSUE TITLE
Regular newsletter

### ISSUE THREAD

**Issue by SabinaChita** [hedyorg/hedy#4108]
A while ago we made a few newsletters. Let's do that again, every month of every two months. For example with:

- new features for Hedy
- a nice idea for a lesson
- an activity (e.g. a talk/symposium somewhere)
- concrete request like a survey with feedback

**Comment by SabinaChita** [comment]
We hebben in MailChimp een paar nieuwsbrieven gedaan (een stuk of 3?) Je kan die via Mailchimp nog wel vinden. Het is een mooie ambitie om ze weer vaker te gaan sturen, bijv iedere maand of 2 maanden. Met bijv deze inhoud:

Nieuwe features
Een leuk lesidee
Een activiteit (zoals als we ergens een praatje gaan geven)
Een concrete ask zoals een survey met feedback

**Comment by Felienne** [comment]
We could use this thread to gather ideas for the newsletter!

For example, a new and exciting feature is the improved customization for teachers @jpelay did in #3854

**Comment by SabinaChita** [comment]
[MailchimpTemplateTestNewsletter.pdf](https://github.com/hedyorg/hedy/files/10999815/MailchimpTemplateTestNewsletter.pdf)

**Comment by SabinaChita** [comment]
https://drive.google.com/file/d/1WdlhBLSYwLFhb_1r2pgMaOMnt2JzYQxI/view?usp=share_link

@Felienne Kan je feedback hierop geven? alvast dank.

**Comment by Felienne** [comment]
Hi @SabinaChita!

As promised I am working on a better pipeline for newsitems, because an issue is supposed to not be long living (so I will close this one)

I made a new board, here: https://github.com/orgs/hedyorg/projects/4

I will put stuff on the board that I think should go in the newsletter, and then you can sync with the author of the PR for content, either in Discord or on the PR or issue. In any case the action to fund content is then with you.

Hope this helps!

**Comment by SabinaChita** [comment]
[like]  Chiță, S.M. (Sabina) reacted to your message:
________________________________
