### ISSUE TITLE
[CONTENT] Intended semantics of keywords (and question about it for Russian language specifically)

### ISSUE THREAD

**Issue by aluuu** [hedyorg/hedy#4181]
**Describe the issue**
While trying to teach a kid the Hedy keywords in Russian I realized that Russian translation of keywords might not match the meaning of them in English (or Dutch). I would like to clarify if this is a real issue or just my perception.

If I'm looking at English or Dutch translations then I see that verbal forms that are used there are not strictly [infinitives](https://en.wikipedia.org/wiki/Infinitive), but verbs are given in the [imperative mood](https://en.wikipedia.org/wiki/Imperative_mood) - when you read `ask what's your name?` or `vraag how heet jij?` I feel (and I may perceive it wrongly) that there's a call for action. Note that it's not `vragen ...` and not `to ask ...`. 

In Russian translation, however, infinitive form of the verb is used everywhere, which reads a bit awkward. If the intention was to make it readable as if the language was close to real language then it didn't work as expected. I've checked Ukrainian translation and there translator addressed this issue in a similar way - imperative forms are used for the verbs.

I'm curious if this is okay to change keywords or it requires extra coordination with the Hedy maintainers? I can change these on weblate, let me know if any extra steps should be taken to make such change.

**Expected text**
I would replace verbal keywords with translations in imperative form. E.g. `печатать` would become `печатай`, `запросить` - `запроси/спроси`, `повторить` - `повтори`, `повернуть` - `поверни`.

**Comment by Felienne** [comment]
This is a great question, but it is not really an issue (so I will be closing it after this)

So far, different languages have made different decisions, since in English it is not so clear whether `print` means imperative or infinitive! In Dutch we have chosen imperative, but Spanish for example uses infinitive because there was prior art of other programming languages doing so. I am not against changing it (I tend to accept what people suggest if I don't know the language) but there might be a reason that Russian is as it is, I don't know!

It is a bit of a hassle, but you can use GitHub history to find the translators, f.e. https://github.com/hedyorg/hedy/commits/main/content/adventures/ru.yaml and https://github.com/hedyorg/hedy/commits/main/content/keywords/ru.yaml show that @thejenja has been doing some of the earlier work and @xretr0. Maybe you can sync with them? 

The best place to discuss translations in more depth is Discord: https://discord.gg/ecjdQ76a (translators channel) You can tag yourself there as a Russian translator so people can find you more easily (I am not sure whether @thejenja or @xretr0 is also there, sometimes people have different handles across platforms, and we did not always have Discord)

Hope this helps!

**Comment by aluuu** [comment]
Indeed, it's not an 'issue', just didn't find better place to seek for a meaningful advice :)

Thanks a lot! I'll then reach out to people at Discord's translations channel and will try finding people who use Hedy in Russian to get their opinions.
