### ISSUE TITLE
[CONTENT?] Introductory code in level 15 hangs

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4345]
This was reported by Zenior on the Discord server:

Level 15 has this introductory code:
```
game is 'on'
for i in range 1 to 100
    if game is 'on'
        answer = ask 'Do you want to continue?'
        if answer is 'no'
            game is 'over'
        if answer is 'yes'
            print 'Ok we will continue'
```
If you answer no, it does nothing and then it says: Your program has been executing for too long. Should we change this a bit so it's more clear that the program is doing something or stop the loop?

**Comment by jpelay** [comment]
What do you think @MarleenGilsing?

**Comment by arjank** [comment]
A range from 1 to 100 fails because it takes too long. There's a `time.sleep(0.1)` added to the end of each loop iteration so at some point you'll hit the timeout limit.

This code seems to fail consistently for the same reason.
```
j = 0
for i in range 1 to 47
    j = j + i
print j
```
And if you only count to 46 it still takes relatively long but it will come up with the correct answer (1081).

**Comment by jpelay** [comment]
> A range from 1 to 100 fails because it takes too long. There's a `time.sleep(0.1)` added to the end of each loop iteration so at some point you'll hit the timeout limit.
> 
> This code seems to fail consistently for the same reason.
> 
> ```
> j = 0
> for i in range 1 to 47
>     j = j + i
> print j
> ```
> 
> And if you only count to 46 it still takes relatively long but it will come up with the correct answer (1081).

Yes, I'm aware, the point of my issue is that maybe we shouldn't put programs in the examples that hang!

**Comment by arjank** [comment]
> > A range from 1 to 100 fails because it takes too long. There's a `time.sleep(0.1)` added to the end of each loop iteration so at some point you'll hit the timeout limit.
> > This code seems to fail consistently for the same reason.
> > ```
> > j = 0
> > for i in range 1 to 47
> >     j = j + i
> > print j
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And if you only count to 46 it still takes relatively long but it will come up with the correct answer (1081).
> 
> Yes, I'm aware, the point of my issue is that maybe we shouldn't put programs in the examples that hang!

Yeah, that would make sense. Just count to 10 instead of 100 and we should be safe. Also we might want to change those for loops so they don't timeout within 50 iterations.

**Comment by jpelay** [comment]
> Member

Good idea, gonna discuss this tomorrow in the meeting!

**Comment by jpelay** [comment]
Thank you for your input Arjan!

**Comment by MarleenGilsing** [comment]
Very late to the party, haha, but the whole point of the example is that it is cumbersome and not effective! It is supposed to convince the students that another way would be better, so they are motivated to learn the while loop instead of just using for i in range 1 to 100 (or something like that to create a loop effect).
