### ISSUE TITLE
[CONTENT] Some remarks in Dutch

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4380]
Feedback van een Nederlandse meelezer (letterlijk gekopieerd)

**Level 1**
Intro​​… code hebt …
vraag​​… na Hoi.  Maar in prg staat hello
steen, papier schaar : Hoe tik je emojis in ?  ctrl-cmd-spatie op MacBook
tekenen​error-melding nog met engelse term right/left. Lastig om alles te voorkomen !
​​zie schermafbeelding 1 en 2
 
Ooit eens alle foutmeldingen doornemen ?? Lastig om alle bugs in foutmeldingen te vinden/voorkomen ? Want maak maar eens alle mogelijke fouten.
NB  Engelse en nederlandse commando’s wertn beide door elkaar.
 
**Level 2**
Intro​​Voorbeeldcode uitvoeren geeft rare foutmelding. Uitvoeren is ook niet de ​​​bedoeling denk.
is​​4e regel tekst : “verplaatst met” ->  vervangt door
​​In voorbeeldcode Opdracht:  favorite_animals >> lievelingsdier
vraag​​tikfout “je” in vb.prg.
​​tikfout “intercatief”
s,p,s2​​tikfout “ckeuze’
Spookhuis​In vb.prg : … daar word je opgewacht …
​​In invulregel binnen browser kan ik geen emoji kiezen met ctrl-cmd-spatie ??
Restaurant​In de toppingvraag wordt eten NIET vervangen door de keuze (pizza / lasagne)
​​Op te lossen ??  Alleen over 2 regels ?
Slepen: ​opdracht sluit niet aan bij geleerde.
 
**Level 3**
Willekeurig:​In uitleg “voeg … toe” ipv “voeg”. Evenzo “verwijder … uit”.
​​2e voorbeeldcode is geen goede om uitgelegde te adstrueren.
​​Verbetervoorstel
​​Beperk vb 1 en vb 2 tot wat in dat blokje uitgelegd wordt , nieuw commando. ​​​Daarna in blok 3 bij opdracht laten combineren.
NB​​ Ook hier weer nederlandse foutmeldingen met engelse termen (bv “ask”).
NB2 ​​Waarom hier al voeg toe en verwijder. Dat staat pas een tabblad verderop.

**Comment by MarleenGilsing** [comment]
I've fixed most of the problems in #4426 . The comments below I didn't fix, because I don't know how or I didn't understand the comment. So this is left:  

Level 1
tekenen​error-melding nog met engelse term right/left. Lastig om alles te voorkomen ! ​​zie schermafbeelding 1 en 2
Ooit eens alle foutmeldingen doornemen ?? Lastig om alle bugs in foutmeldingen te vinden/voorkomen ? Want maak maar eens alle mogelijke fouten.

Level 2
​​In invulregel binnen browser kan ik geen emoji kiezen met ctrl-cmd-spatie ??
​​Op te lossen ?? Alleen over 2 regels ?

Level 3
NB​​ Ook hier weer nederlandse foutmeldingen met engelse termen (bv “ask”).

**Comment by Felienne** [comment]
Thanks for the great work! I checked 2 and I can enter emoji so I think that might be a fluke.

For level 1, indeed in level 1 you get an English error:

<img width="622" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/8f97aeef-67be-428d-94f6-4fa8b3dd3ffa">

I think this is just a matter of  this not being translated? Could you take a look next week @MarleenGilsing?

Voor level 3 heb ik het zelf niet kunnen vinden (en er was geen plaatje bij) maar deze persoon is tamelijk zorgvuldig dus misschien kan je nog eens een keer rondklikken in level 3 met iets van ask? Of de foutmeldingen lezen in weblate en kijken of we er eentje missen?

Ik laat deze dus nog even open staan voor jou!

**Comment by MarleenGilsing** [comment]
@Felienne 
I found the level 3 mistake 'ask' ipv 'vraag'
![image](https://github.com/hedyorg/hedy/assets/80678586/9fad6dd9-d341-4847-b7e8-dd53ed2e9646)

I think it has to be solved here, but I don't know how to make the "offending_keyword" localized. So I'll leave this one to you. 
![image](https://github.com/hedyorg/hedy/assets/80678586/17656c94-d43c-42b2-8507-9a9f3ba83683)

The left and right problem seems to me as the same problem, because they are translated in the keyword file.

**Comment by Felienne** [comment]
> @Felienne I found the level 3 mistake 'ask' ipv 'vraag' ![image](https://user-images.githubusercontent.com/80678586/267880497-9fad6dd9-d341-4847-b7e8-dd53ed2e9646.png)
> 
> I think it has to be solved here, but I don't know how to make the "offending_keyword" localized. So I'll leave this one to you. ![image](https://user-images.githubusercontent.com/80678586/267881319-17656c94-d43c-42b2-8507-9a9f3ba83683.png)
> 
> The left and right problem seems to me as the same problem, because they are translated in the keyword file.

Fantastic, thanks! I will make a fresh issue and pick ip up, this can be closed!
