### ISSUE TITLE
[BUG] The content files in all laguages should use 4 spaces as standard indentation

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4484]
Currently there are some content files (like adventures, quizzes and puzzels etc) that use 4 spaces as indentation (like our english files do), but some translators created files with 2 space indents. There are also files in which the content isn't using enters, but \n. 

All this variation in the files makes it hard to make changes in other languages that are only partly translated.  

Another thing that complicates adding new content or changes to (partly) translated files is that each file uses a different order of headings. For example: In English all the quizzes go from question 1 to 10, but some other files can go 1,5,3,2,8,9,10,7,6,4. In quizzes, this is not really a problem because you can still see the number so you know which heading this is. But in the teacher manual, all the headers are translated so you can't easily see which header is which. That makes it hard to make changes to the content.

**Comment by jtwaleson** [comment]
@MarleenGilsing do you have an example of these files? We can probably build a small linter to fix this (auto-indent and strict ordering).

**Comment by Felienne** [comment]
> @MarleenGilsing do you have an example of these files? We can probably build a small linter to fix this (auto-indent and strict ordering).

Here is an example, of a mix of 4 and then 6 spaces.

<img width="680" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/0df7f993-48a3-406f-b627-7ea1a789b8b8">

(screenshot around https://github.com/hedyorg/hedy/blob/84e536eef0e0af3ea5167a644d0646f8439f20e0/content/adventures/ar.yaml#L157)

Related is that sometimes, the yaml fields also have |2 (meaning indentation 2) even when they use 4 spaces:

<img width="757" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/1e57bf6d-0762-40a9-a99a-a423d8c4b7c9">

(source: https://github.com/hedyorg/hedy/blob/84e536eef0e0af3ea5167a644d0646f8439f20e0/content/adventures/bn.yaml#L950)

This can mess up tests, because our yaml reader than gets in 2 extra spaces, causing the test parser to break (if you don't totally understand that, that does not matter, the core issue is that the |2 should not be there. I am not sure why it occurs (probably from Weblate) but removing them fixes some tests issues!

**Comment by jtwaleson** [comment]
Mental note:  this is included in #4557 . If we decide to implement that and apply the script, I believe we can close this issue too.

**Comment by jtwaleson** [comment]
@Felienne this can be closed :)
