### ISSUE TITLE
[CONTENT] Restaurant level 13 example code is wrong?

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4567]
I should fix it.

**Comment by yilmazdurmaz** [comment]
Let me help.
On weblate, this adventure's code seems to have lost its first 4 lines 6 months ago for no apparent reason. here they are

````
price = 10
food = {ask} 'What would you like to eat?'
drinks = {ask} 'What would you like to drink?'
{if} food {is} 'sandwich' _ drinks {is} 'juice'
    {print} 'That is our discount menu'
    price = price - 3
{if} drinks {is} 'water' _ drinks {is} 'juice'
    {print} 'That is a healthy choice'
{print} 'That will be ' price ' dollars'
````

I am yet to finish my own language translations, but closing in. When I am done the first run through, I too will try correcting such problems.

A Tip (if you didn't know): Instead of creating a commit on Github, if  you edit this on Weblate, it will distribute faster to all languages. Then Weblate, will both mark every language as "needs editing" and include the changes in translation commits. pretty nice.

this one is here: https://hosted.weblate.org/translate/hedy/adventures/en/?checksum=fc258163a67675ad

I copy pasted parts of the code above from different parts in history. there were some corrections. check if the code above as is now. when it is correct, you can directly copy-paste onto Weblate.
