### ISSUE TITLE
[UI] Confusing go to level 2 button

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4606]
The discussion below makes a great point! The funny thing is, that the "go to level" button predates the tabs, so it made sense in the beginning and we just never changed it!

But the correct logic should totally be to go to the next tab, and only show "next level" at the last one!

### Discussed in https://github.com/hedyorg/hedy/discussions/4358

<div type='discussions-op-text'>

<sup>Originally posted by **markusgeert** June 21, 2023</sup>
The button `Go to level 2` can be confusing for beginners, since they expect to go to the next tab. Maybe a better idea would be to replace it with a `Go to next tab` button, and add the button for going to the next level at the end of the tab list? </div>

**Comment by jtwaleson** [comment]
My son found this confusing too :) So just to be sure, the intended way is to go through to all the tabs sequentially and then to the next level?

**Comment by yilmazdurmaz** [comment]
> Alternatively we can make the "Level x" header in the action bar into a dropdown

I had this in mind to ask quite some time. I would vote for this expression implemented even if you put another button to solve the issue ;)

**Comment by TiBiBa** [comment]
> > Alternatively we can make the "Level x" header in the action bar into a dropdown
> 
> I had this in mind to ask quite some time. I would vote for this expression implemented even if you put another button to solve the issue ;)

Awesome! I will look into this today.

**Comment by yilmazdurmaz** [comment]
Deciding UI is hard :) here are a few more ideas:
- we may leave the upper "Level X" label alone, and make the dropdown at the very bottom, at a distinctive distance from editor area, along with "next/prev level" buttons around it. teachers and translators will much benefit this.
- "go to next/prev adventure" name might be better than "go to tab"
  -  or use the actual adventure names like: `Next/Previous Adventure\n{next_tab_name}` (next_tab_name is made up)
  - this may better help self-learners to stay in line, instead of thinking where to go next.

**Comment by michaelficarra** [comment]
I was also confused by this UI. I think due to the placement of the buttons, I didn't realise they were a "higher level" navigation than the tabs. Hiding them when not on the first/last tab would help me understand, but I would still like the ability to navigate levels in one click. Maybe move them to the left/right of the tabs and de-emphasise them with colour choice when the first/last tab are not selected? Kind of like what @TiBiBa suggested but buttons instead of tabs.

**Comment by Felienne** [comment]
Because of the Hour of Code project, we need to move this forward quickly. @TiBiBa, do you think you have time today/this weekend? If not, someone else will do it, sorry!

**Comment by Felienne** [comment]
Closed by #4714
