### ISSUE TITLE
[CONTENT] Some languages miss password reset link

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4630]
In some languages, the text for the password reset email misses the `{link}` part, meaning people can't reset their passwords, see:

https://hosted.weblate.org/translate/hedy/web-texts/it/?q=Richiedi+di+resettare+la+password&sort_by=-priority%2Cposition&offset=1

This problem needs a two step solution:

1. Reset the missing texts to English (or translate manually with Google translate, in this case I think machine translation would be fine since it is short and not often used)
2. Make sure this does not happen again. I think we can do this in Weblate with a mandatory text element?

**Comment by Felienne** [comment]
Maybe @yilmazdurmaz would like to do step 1?

And I guess 2 is something that @Mark-Giesen could look into?

**Comment by Mark-Giesen** [comment]
> And I guess 2 is something that @Mark-Giesen could look into?

Done, because there was never code in the PO files and {xxx} equality is, normally, a coding thing, this was not enforced on the PO files, now it is. Enforcing means that the string will remain in "needs editing" state until solved. Like all other checks, we can not yet deny translators saving the translation.

**Comment by Felienne** [comment]
Closed by #4628
