### ISSUE TITLE
[BUG] Save name is empty

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4640]
For some adventures (print in level 1, for example) the default save name is empty (the blue bar next to level)

<img width="1337" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/1b20d2de-fa9e-4027-89aa-8b665c7de1fb">

I don't think this leads to problems (f.e. I can just save this program: https://hedy.org/hedy/67df965c89934be384a3c46a363b102f/view)

But it does look weird and maybe there are issues.

**Comment by Felienne** [comment]
As @yilmazdurmaz said, maybe (not sure!) this has to do with empty strings: 

https://hosted.weblate.org/translate/hedy/glossary/et/?checksum=874cd1659d00f0a1&q=target%3Ar%22%5E%5Cs%2A%24%22&sort_by=-priority%2Cposition

**Comment by yilmazdurmaz** [comment]
I made a bit more check on Weblate. The string you linked, unfortunately, not about save names.

As far I can tell, save names are part of stories in adventure files with "default_save_name" key, but none of the languages have any empty string with this key. Is there any other yaml key you use for saved programs? 

However, there is a strong possibility I had before: the user cleared the save name box because it is not actually hinted as being the file save name.

check this program, for example, I just saved with empty name: https://hedy-alpha.herokuapp.com/hedy/32700b9ad2f14c5db3f1b96bb5f79182/view
