### ISSUE TITLE
mixed-script numeric literals should be rejected

### ISSUE THREAD

**Issue by michaelficarra** [hedyorg/hedy#4671]
I don't believe there's any reason that someone would want to mix scripts within a single numeric literal. I think it's more likely that some sort of mistake has occurred. The program `print(4٤৪೪๔᥊᮴꘤)` contains a numeric literal with each digit taken from a different decimal numeral system. This incantation wouldn't be recognisable to any human. Currently, it produces `44444444`, but I think it should error.

**Comment by Felienne** [comment]
Ah I love this issue because it is making me realize there are so many think about about Hedy.

One code design goal (which is guess we should document better) is that we want to be execture as many programs as we can!

With designing error messages, I think we have two reasons to give them:

1. Because the parser is confused and we have to communicate why
2. Because we think an error message can teach something needed in real programming life (brackets, quotes, spaces)

To be honest, I don't think anyone made *this specific* decision consciously with these in mind, so maybe I am retconning here, but I think I like the fact that this works? Kids that are coming for bilingual/bicultural contexts might want to mix, or might accidentally mix systems (we aim at 10+ year olds who are not as proficient in many things as adults). Something like `print (1٩)` really is not as weird as your example and can be a result of confusion or of accidentally mixing (software) keyboards and then glancing over it and seeing it look ok.

Coming back to the reasons, clearly 1 is not true here, so the question is, is 2? Do we want to enforce kids to not mix because this is needed later, and if we do, at what level? In level 18 when we are, more or less, Python? Or right at level 6 when we introduce number, or in between? 

These are interesting things to ponder because they are fun for us as creators (so by all means, chip in!) but in the end, I think for our users/use base, we are doing the right thing here, esp in the earlier levels.

**Comment by michaelficarra** [comment]
That makes sense! Coming from outside the world of education, I had never even considered a multilingual user who wasn't aware that they were mixing numerals from different scripts in a single numeric literal. I'm interested to see what you come up with here (and the rationale).
