### ISSUE TITLE
[BUG] Tab key doesn't seem to work in Hedy anymore?

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4830]
Maybe this is just me and my computer, but the tab key on my keyboard doesn't seem to work anymore when typing code in Hedy. If i want to use indentation I need to type 4 spaces instead of one tab. When i use tab I select the variables label in the output screen. 

If it's just me, the issue can be closed (if you know a solution, I'd still like to know). If not, we might want to come up with a solution.

**Comment by jpelay** [comment]
> Maybe this is just me and my computer, but the tab key on my keyboard doesn't seem to work anymore when typing code in Hedy. If i want to use indentation I need to type 4 spaces instead of one tab. When i use tab I select the variables label in the output screen.
> 
> If it's just me, the issue can be closed (if you know a solution, I'd still like to know). If not, we might want to come up with a solution.

Hi! This was an intended change! When we made the change to our new editor, we decided that tab would now work as every other element in the browser: to change focus to other elements, otherwise the input becomes a trap and users that don't use pointing devices to navigate through the page can't switch focus. This means also that we're are compliant with this directive from the W3: https://www.w3.org/TR/WCAG21/#no-keyboard-trap

**Comment by MarleenGilsing** [comment]
Ah I see... 

We might want to rethink it though, because using a tab is very handy while having to count to 8 or even 12 spaces (in the higher levels) is very cumbersome.

**Comment by jpelay** [comment]
> Ah I see...
> 
> We might want to rethink it though, because using a tab is very handy while having to count to 8 or even 12 spaces (in the higher levels) is very cumbersome.

We are working on automatically tracking previous indentation, so users would only need to manually add indentation once per block. Would that be a better solution?

**Comment by hasan-sh** [comment]
> > Ah I see...
> > We might want to rethink it though, because using a tab is very handy while having to count to 8 or even 12 spaces (in the higher levels) is very cumbersome.
> 
> We are working on automatically tracking previous indentation, so users would only need to manually add indentation once per block. Would that be a better solution?

I think this will be a bit cumbersome and don't really agree that if we map the tab key to indenting code, we would trap the user within the editor. And we would still meet the accessibility criteria.

The solution would be to introduce an exit key so that users can unfocus the code editor. Naturally, when users focus on a subsection and want to only use keyboard, they click on the escape key to unfocus. This is actually the case now! By that, we actually are compliant with this accessiblity and thus more inclusive:
> **There may be times when the functionality of the Web page restricts the focus to a subsection of the content, as long as the user knows how to leave that state and "untrap" the focus.** read more -> https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html

**Comment by MarleenGilsing** [comment]
> The solution would be to introduce an exit key so that users can unfocus the code editor. Naturally, when users focus on a subsection and want to only use keyboard, they click on the escape key to unfocus. This is actually the case now! By that, we actually are compliant with this accessiblity and thus more inclusive:
> 
> >

Perfect solution!
