### ISSUE TITLE
[UI] Localized program titles 

### ISSUE THREAD

**Issue by Annelein** [hedyorg/hedy#4847]
The title of a program is not localized. 

<img width="1429" alt="Screenshot 2023-12-04 at 20 05 15" src="https://github.com/hedyorg/hedy/assets/48122190/4e746656-4509-42e5-b09a-231f7b5e0f33">

**Comment by Felienne** [comment]
Is this maybe a content issue rather than a code issue? Because it sometimes is localized:

<img width="759" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/442b424b-4ad5-4d5a-b9eb-b2a12a7b79d4">

It might also be that you have once run a program in that tab in English (triggering a save with the current name!) and then switched languages. It then keeps the name of the program, each tab has its own name that you can change if you want to.

**Comment by Annelein** [comment]
> It might also be that you have once run a program in that tab in English (triggering a save with the current name!) and then switched languages. It then keeps the name of the program, each tab has its own name that you can change if you want to.

that's it!
