### ISSUE TITLE
🪲 Allow for closing of levels before a quiz

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5046]
For a teacher's email:

"Ik ga in februari met mijn leerlingen aan de slag met Hedy, maar ik ben op een programmeerfoutje gestuit. Ik wil namelijk dat mijn klassen gelijk beginnen met Level 2 van de cursus. Maar toen ik in mijn toegevoegde “klas” Level 1 had dichtgezet, kon ik in het voorbeeld (wat de leerlingen zien) niet bij Level 2 (of elk ander level). Ik heb namelijk de levels dichtgezet, totdat een leerling het minimale percentage van 75% haalt bij de Quiz van het vorige level. Omdat ik de Quiz van Level 1 niet had gemaakt, kon ik dus niet bij Level 2. En omdat ik Level 1 dicht heb gezet, kunnen mijn leerlingen de Quiz van Level 1 niet maken.
 
Ik hoop dat dit wellicht veranderd kan worden, zodat een minimaal percentage bij de Quiz niet hoeft te betekenen dat levels niet dichtgezet kunnen worden."

This is a bit of a tricky edge case that we did not think of: closing a level without having students go through it. I am not sure how to easily fix this in terms of UI and also data.

**Comment by hasan-sh** [comment]
So the expected behavior from the teacher's perspective is:
- i create a class that have X students.
- i want my students to skip level Y
- **any quiz threshold shouldn't be enforced on disabled levels**

Am I thinking right? If so, this does affect quite some code indeed! But I'm not sure if we need to do anything wrt the UI, perhaps in the teachers manual we could explain this behavior?
