### ISSUE TITLE
💻 Redesign program page

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5112]
I worked on this, like hiding the second actions and just showing the main ones like submit and open. Deleting, copying and share would be hidden in that menu. Also, I thought about changing the share button for a drop down that says private or public. Just like i'm showing on the images. 

![Frame 7](https://github.com/hedyorg/hedy/assets/154460618/8713c989-f6de-4f23-9d3e-ceb59dcd9354)
![Frame 6](https://github.com/hedyorg/hedy/assets/154460618/008bbc42-b659-4d21-86bd-cbcc6a6aa0e1)

_Originally posted by @gisellandrade in https://github.com/hedyorg/hedy/issues/5045#issuecomment-1934625987_

**Comment by gisellandrade** [comment]
I added the copy button in the frame of the code. So this way would be cool and easy to understand. Let me know your comments 😃 

![Propuesta #1](https://github.com/hedyorg/hedy/assets/154460618/54070cc8-b1ac-40ad-bbbd-f3e95379c278)
![Propuesta #2](https://github.com/hedyorg/hedy/assets/154460618/22a0f048-3889-4a88-8d38-b083ada8aa7d)

**Comment by Annelein** [comment]
Hey @gisellandrade , thank you for making these!

- I think I might prefer option 2 because it feels like 'Private' and 'Public' make more sense then 'Share' and 'Unshare'. But I would then prefer it without icons because none of the other buttons have icons. Let me know what you think!

- Also, favouriting a program is added, which is located right at the menu button:
<img width="1440" alt="Screenshot 2024-02-12 at 10 11 02" src="https://github.com/hedyorg/hedy/assets/48122190/7cad7e52-d27b-4406-9eda-90d2117e3d9b">

Are you using hedy.org? Maybe it would be nice to set up the environment so you can see the latest changes?

@jpelay @hasan-sh what are your thoughts?

**Comment by hasan-sh** [comment]
> * @Felienne @jpelay @hasan-sh what are your thoughts?

I also prefer option 2. Also, I'd remove the outline and add a box shadow to the entire block. Perhaps enable the outline only when the user hovers over it, not necessary!

**Comment by Felienne** [comment]
I am not entirely sure what options 1 and 2 are, but I would prefer buttons instead of the ... because the .. are too hidden for kids I fear?

**Comment by Felienne** [comment]
> Also, I believe that if we use a lot of buttons below the code rectangle, we are going to have a lot of buttons and instead of giving them solutions, we are going to overwhelmed them.

Yes that is also true! If we explain the dots well, it could work!

**Comment by gisellandrade** [comment]
This is the final design, the one that I showed you in tuesday's meeting!! I'm to leave it for granted as it was the final version and resolution of this issue from my side.

![final](https://github.com/hedyorg/hedy/assets/154460618/4b6f5c24-f555-4ee8-80a3-6cc641fc2a56)

**Comment by Annelein** [comment]
I will start implementing it
