### ISSUE TITLE
🪲 display problem in quiz response page when displaying code

### ISSUE THREAD

**Issue by etienneCharignon** [hedyorg/hedy#5129]
**Describe the bug**
in the quiz, after you answer a question, a result page is displayed. This result page contains the right answer. If this answer is a block of code, it should not be formatted "centered". Because so, the indentation that might be the important element of the answer is not readable anymore.

Attention that we might want to keep it centered when it is not a block of code.

**Paste the Hedy code & level**
This appears, for example, in the quiz at level 11, questions 3 or 11

**Add a screenshot (optional)**
<img width="667" alt="Capture d’écran 2024-02-11 à 15 26 07" src="https://github.com/hedyorg/hedy/assets/298214/f795e902-bbb2-4b7a-82a4-b6318b8cefa9">

<img width="1164" alt="Capture d’écran 2024-02-11 à 15 29 16" src="https://github.com/hedyorg/hedy/assets/298214/e9fd34a4-a42c-4d47-8947-eb9ce779e990">

An example without a block of code, that might stay centered : 
<img width="606" alt="Capture d’écran 2024-02-11 à 15 26 47" src="https://github.com/hedyorg/hedy/assets/298214/cebce630-0356-48e8-91b4-acbbf4045502">

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using : Mac
- What browser you were using : Firefox

**Comment by Felienne** [comment]
Ah great find!! Should be not all too hard to fix (maybe for @Annelein?)

**Comment by pzrq** [comment]
I'm new to Hedy (great project and [YOW! talk](https://www.youtube.com/watch?v=j4eSjA6btE8), thanks!), so hopefully this is helpful. I've cloned and set up Hedy locally.

I did some digging to hopefully establish a few more pieces of context:
1. The relevant front end code looks to be this, for example if I drop the `text-center` Tailwind class from Line 30, I'd have an incomplete fix: https://github.com/hedyorg/hedy/blob/b7acb4d665ced025897400191eeab5d074ace17f/templates/quiz/partial-review-question.html#L30-L41
2. In the back end code, I was able to add an `import pdb; pdb.set_trace()` after this line, and type `continue` (or the shortcut `c` and the enter key) in my local `doit run devserver` after answering Level 11 Q1/Q2, to get to Q3: https://github.com/hedyorg/hedy/blob/111e205343f814457f6b19289ac3faa9e7cbdcb5/website/quiz.py#L133
3. Answering Q3 and asking Pdb for the value of `correct_answer` outputs for me, for example:

```
> (Pdb) correct_answer
Choice(number=1, text="```\nfor i in range 1 to 5\n    print i\nprint 'Once I caught a fish alive!'\n```", feedback='Perfect', code=None)
```

4. The Choice dataclass: https://github.com/hedyorg/hedy/blob/111e205343f814457f6b19289ac3faa9e7cbdcb5/website/quiz.py#L309-L314

So to me, it looks like `code` can be put into the `text` field. 

Is there a [spec](https://www.joelonsoftware.com/2000/10/03/painless-functional-specifications-part-2-whats-a-spec/)  beyond that dataclass, or some way of determining if what looks like `code` inside `text` is intentional, and so should be supported, somehow? Or is it that `code` and `text` quiz answer choices should be authored such that this ideally wouldn't happen?

**Comment by Felienne** [comment]
A small issue for @hasan-sh to pick up, maybe!
