### ISSUE TITLE
🪲 warningbox is shown if multi classes dropdown is changed

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#5290]
**Describe the bug**
![image](https://github.com/hedyorg/hedy/assets/20051470/bb6d702c-01f3-4110-a0a0-98b3276af763)

![image](https://github.com/hedyorg/hedy/assets/20051470/f7b55a8b-b5cf-4823-b453-4a17f0a28125)

@jpelay ?!

**Comment by jpelay** [comment]
> @jpelay ?!

I was checking all of the HTML elements that had aria-selected=True and now that this page has two selects, it got messed up 😆

**Comment by jpelay** [comment]
So this is what happened: since (as far as I know) there's no way to target the `id` of the `div` tw-elements generates when displaying the selects, I targeted all of the elements that had this field: `'[data-te-select-option-ref]'`. Since now there are two of these selects in the page, my selector targets the first one and now the event handler is messed up. I made a question in the GitHub page of the library, but if you have any ideas as to how to do this, they'll be more than welcomed!!

**Comment by hasan-sh** [comment]
Yeah, for now we could just make the selectors more specific. Perhaps by adding a div with an id as a wrapper to the select element we want your event to listen to:)

**Comment by jpelay** [comment]
> Yeah, for now we could just make the selectors more specific. Perhaps by adding a div with an id as a wrapper to the select element we want your event to listen to:) Could you share the link to your question on their github page?

Here it is: https://github.com/mdbootstrap/TW-Elements/issues/2333 They told me to check the API page of the element, but to even view the documentation I need a paid account. I honestly think the best way forward would be to replace this library for a free one, or maybe even our own solution, because we can't even use many of the features with a free account :C

**Comment by jpelay** [comment]
> It was free when i used it. Really annoying that it isn't now! Let's discuss it tomorrow! But i think the solution i suggested would solve our problem for now!

TW Elements generates the dropdown dynamically, so there's no way to target it externally, I tried multiple things to no avail. The div that actually changes has an id that is generated at runtime. Tomorrow we can keep discussing this!

**Comment by hasan-sh** [comment]
@jpelay check out this related comment by @Felienne https://github.com/hedyorg/hedy/pull/5385#pullrequestreview-1989688012
