### ISSUE TITLE
🪲 program overview page breaks when program is too long

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#5314]
**Describe the bug**
Here's the bug from the logs:

![image](https://github.com/hedyorg/hedy/assets/20051470/ba07e6d6-cf0f-4b25-ab26-883d068a4168)

**Why?**
I suspect that it has to do with the SequenceMatcher we used to get a ratio of similarity. I'm tagging you @jpelay here to look at it as well.

**Comment by Felienne** [comment]
Check if this is still the case, is not close.

**Comment by jpelay** [comment]
I'm going to work on this since I have more experience with this part of the code, Boryana will check the issues related to the DB

**Comment by jpelay** [comment]
By the way, here are my advances:

I don't think this has anything to do with the program being too long, the real problem is shown in the stacktrace:

```python
return self.attrs[key]

KeyError: 0
```

This error points to the BeautifulSoup library which we use to parse the html code that makes the teacher adventures. The previous line in the stack trace gives a hunt what this might be about:

```python
 for j in b2j.get(a[i], nothing):
```

This means that we are indexing most likely trying to index a BeautifulSoup object as if it were a string, and then the keyerror happens.

**Comment by jpelay** [comment]
So the problem happened when there were HTML tags inside the code snippets in teachers adventures, this doesn't happen now because we use the CKEditor, but since the change is very small I will still make a PR so that legacy adventures don't experience this issue.
