### ISSUE TITLE
🪲 Make `adventure_name` necessary when storing a program

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#5458]
**Describe the bug**

 There was an error a few days ago related to programs being stored with adventure_name set to `None`.  I think we should make them necessary every time we store a program.
 
 This also entails not storing programs from the embedded editor and parsons.

**Comment by Felienne** [comment]
High prio to check if this is still an issue? It can lead to a lot of errors so it would be good to fix it and also check the DB how we deal with programs that don't have an adventure name?

**Comment by jpelay** [comment]
> High prio to check if this is still an issue? It can lead to a lot of errors so it would be good to fix it and also check the DB how we deal with programs that don't have an adventure name?

When we made the types schemas to check the types of the db, I added this field as required, so far it hasn't come up. I'm right now checking the db to see if there are any recent programs that don't have that field, tomorrow I'll try to make a query, because doing it through the console is way too slow!

**Comment by boryanagoncharenko** [comment]
I am afraid there isn't an easy, inexpensive way to check in the DB whether there are programs without adventure_name attribute set. We will need to make a full scan of the programs table which could be a lengthy and expensive procedure. (Why? We do have a global secondary index on adventure-name and date. However, based on my grasp of sparse indexes, the index will not contain the records with missing adventure-name, so we are basically looking for the records which are not in this index. @rix0rrr, correct me if I am wrong here and also if there is another scan-less approach to pinpoint programs without adventure names.)

I probed the logs for errors caused by adventure-nameless programs and I was not able to find any related errors. So, at least we know that if such errors occur, their magnitude is not large.

I tested all routes (that I know) for saving, submitting and sharing programs and it seems that we do supply an adventure name in all of them. However, I also noticed the adventure_name is not required in the request for the backend endpoints. Perhaps we should make that explicit?

Wouldn't a simpler solution be to supply a default value in case we fetch a program which does not have an adventure_name set? Something in lines of:
```
def program_by_id(self, id):
    result = self.programs.get({"id": id})
    result["adventure_name"] = result.get("adventure_name", "default")
    return result
```
@jpelay would this be a working option or would that have undesirable side-effects?

**Comment by rix0rrr** [comment]
> @rix0rrr, correct me if I am wrong here and also if there is another scan-less approach to pinpoint programs without adventure names.

There is no other way. But with the data sizes that we have (~500k items, 240MB), I'm absolutely not scared of table scans to correct some data integrity issue. We shouldn't be resorting to scans as a matter of course in the interactive handling of requests on hedy.org.

But a one-off scan to add in some column for all records that need it? Sure, go right ahead.

It would take 500k read request units, and let's say 10% of items so 50k write request units to do this scan. About $0.04 for the reads and $0.14 for the writes, and at a conservative estimate of 5 pages/second it would be done in just under a minute.

The following line is making supplying an `adventure_name` required for all programs, so I don't think new programs without any `adventure_name` will be written to the database:

https://github.com/hedyorg/hedy/blob/efe00f5924297510436a95c11272c14498316069/website/database.py#L136C1-L137C1

(Of course, since that type check is not in effect in production mode, we only check that for code that is actually exercised during tests... untested code that was written before this type check was in place will not be tested that way)

**Comment by boryanagoncharenko** [comment]
Executed a script adding an adventure_name attribute to all programs which had it missing. On alpha the updated records are 17 and on beta - 15344. Their adventure_name is set to `default`. I am not sure what would be a good approach to test. Let me know your preferences.

**Comment by rix0rrr** [comment]
I think with a code review this should be safe enough. Since we don't have a good canonical source location for migration scripts yet, can you just paste it here? I'll say "looks good" and then you just run it 😄

**Comment by boryanagoncharenko** [comment]
This is my script; let me know if you have concerns

```
def main():
    client = boto3.resource('dynamodb', region_name=region)
    table = client.Table(table_name)

    # scan(table)
    # update(table)


def store_last_value(v, file):
    with open(file, "w") as f:
        json.dump(v, f)


def get_last_value(file):
    if os.path.isfile(file):
        with open(file, 'r') as f:
            return json.load(f)
    return None


def save_items(items):
    ids = [i['id'] for i in items if 'adventure_name' not in i]
    if ids:
        with open(scan_res_file, "a") as f:
            f.write('\n'.join(ids))
            f.write('\n')


def scan(t):
    last_key = get_last_value(temp_scan_file)
    if not last_key:
        response = t.scan()
        save_items(response['Items'])
        last_key = response.get('LastEvaluatedKey')

    try:
        while last_key:
            response = t.scan(ExclusiveStartKey=last_key)
            save_items(response['Items'])
            last_key = response.get('LastEvaluatedKey')
    except Exception as ex:
        print(ex)
        if last_key:
            store_last_value(last_key, temp_scan_file)


def update(t):
    last_id = get_last_value(temp_update_file)

    with open(scan_res_file) as file:
        for line in file:
            pid = line.strip()
            if pid == last_id:
                last_id = None
            if pid and not last_id:
                try:
                    t.update_item(
                        Key={'id': pid},
                        UpdateExpression="set adventure_name = :v",
                        ExpressionAttributeValues={':v': 'default'}
                    )
                except Exception as ex:
                    print(ex)
                    store_last_value(pid, temp_update_file)

if __name__ == "__main__":
    main()

```

**Comment by rix0rrr** [comment]
Ooh, you did everything yourself! I usually go and use the Dynamo helpers we already have:

```py
from website.database import Database
from website import dynamo

db = Database()

for program in dynamo.ScanIterator(db.programs):
    if program.get('adventure_name') is None:
        print(program)
        db.programs.update(...)
```

**Comment by rix0rrr** [comment]
The stateful scanning with crash protection you are doing is neat!

"Looks good". Run it!

**Comment by boryanagoncharenko** [comment]
Thanks for looking into it. It has been executed.
I probed updated records in the DB and they look OK. Logs do not show anything extraordinary.
Let me know if you want to do additional checks.

**Comment by rix0rrr** [comment]
Nope, sounds good!

**Comment by boryanagoncharenko** [comment]
Can we close the issue or are there further aspects that need to be addressed?

**Comment by rix0rrr** [comment]
I'm not sure. There's this one sentence from Jesus' original report that I'm not sure we addressed:

> This also entails not storing programs from the embedded editor and parsons.

If you think we did, then go ahead an close it.

**Comment by boryanagoncharenko** [comment]
Programs are saved via 2 mechanisms:
- auto-saving which stores programs logged users only (programs of anonymous users are stored locally)
- parsing/sharing/submitting/handing in (for shorter, just parsing) a program only for logged users 

I investigated how the above mechanisms work in the following cases:
- Embedded editor (/embedded/<int:level>) - the endpoint serving the embedded editor explicitly forgets the current user, so that parsing a program does not save it. Programs cannot be shared or submitted via the embedded editor. Additionally, the embedded editor has no auto-saving mechanism attached.
- Parsons - the auto-saving is disabled for parsons because they do not have a save_name. Saving while parsing works and we provide an adventure_name “parsons”. Parson programs cannot be shared or submitted.
- Slides (‘/render_code/<level>/‘) - the auto-saving of programs is explicitly suppressed in the editor used in slides. Parsing a program does not save it because even though the user is logged in, there is no `save_name` provided. Programs cannot be shared or submitted via slides.
- Hour of code - both mechanisms work as expected and save programs successfully.

@jpelay could you please review the above investigation? Are there any other scenarios you can think of? Or a different aspect of saving programs that is missing?

**Comment by jpelay** [comment]
I just corroborated @boryanagoncharenko's investigation and she's correct. Furthermore, the other two places where there is an editor also don't save programs: the editor that lets you try the adventure you are writing, and the public adventure editor (in this last case they are saved locally, but not in the DB)
