### ISSUE TITLE
[WEBLATE] Blank strings in multiple languages + String updated in the repository issue

### ISSUE THREAD

**Issue by Kamborio15** [hedyorg/hedy#5890]
**Describe the issue**
There are 5 blank source strings in Weblate project (Adventures section) in multiple languages (i have checked source English, Spanish and French) referring the following levels:

adventures->turtle_draw_it->levels->1->example_code
adventures->turtle_draw_it->levels->2->example_code
adventures->turtle_draw_it->levels->3->example_code
adventures->turtle_draw_it->levels->7->example_code
adventures->turtle_draw_it->levels->8->example_code

And another issue is that recently when a 'String updated in the repository' event updated the source string, every string with an existing translation is overrided back to English, so the language translation is deleted (still reachable over History tab)

**Add a screenshot (optional)**
![image](https://github.com/user-attachments/assets/e480a32c-3368-41ac-a7a7-d303538f4035)

**Expected text**
In other translation projects when a source string is updated the string keeps the original translation and it is marked as 'Needs editing' instead of overriding the already existing one.

**Comment by boryanagoncharenko** [comment]
Thank you for the bug reports.

I suspect the example_code of the turtle adventure is supposed to be empty because there is an image of the shape that needs to be drawn. @MarleenGilsing is this true or are we missing example codes for this adventure? If my assumption is correct, I will remove them from the file, so that they do not appear for translation in Weblate.

Apologies for the overwritten translation. We are using the prefill add-on of Weblate, which is why upon change, we replace the value in all untranslated files and we accidentally removed this translation. I will do my best to restore the values.

**Comment by MarleenGilsing** [comment]
You are right @boryanagoncharenko! These adventures don't have an example code.
