### ISSUE TITLE
💻 Show "Waiting for a button press.." under the output field

### ISSUE THREAD

**Issue by AnneliesVlaar** [hedyorg/hedy#5946]
The text "Waiting for a button press.." when using the 'if key pressed' functionality is placed on top of the output screen. This prevents from seeing the text:

<img width="736" alt="Scherm­afbeelding 2024-11-16 om 13 29 25" src="https://github.com/user-attachments/assets/e959be0a-e15d-49b1-999a-8d39449aed62">

Suggestion is to place the text "Waiting for a button press.." under the output screen by showing a smaller output screen.

**Comment by boryanagoncharenko** [comment]
This is a very unpleasant problem. It is very easy to run into it if you are testing if-pressed together with loops. Unfortunately, this is also not an easy problem to address because I cannot think of a visually nice way to display the 'waiting for a key press' message. Reopening the issue and assigning it to myself.

**Comment by AnneliesVlaar** [comment]
When the error message is shown, it looks like the input screen is moved up and the error message is really below the input screen. 
<img width="736" alt="Scherm­afbeelding 2024-12-06 om 09 42 59" src="https://github.com/user-attachments/assets/4867656c-6484-476d-8dd5-b23303e3fda7">

Could we use the same mechanism for the waiting for a button press ... ?

**Comment by boryanagoncharenko** [comment]
If you look at the screenshot in #3856 it seems that this was the layout before. So, this is the way to go :)

**Comment by Felienne** [comment]
This seems to be a problem with the input field too!

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/262feebd-0860-4e2e-b546-e31d7507e345">

I vaguely remember we had an issue open for this before but I can't find it now.

**Comment by AnneliesVlaar** [comment]
I am not sure if I understand what you mean. Can you describe 'This' in 
> This seems to be a problem with the input field too!

?

**Comment by boryanagoncharenko** [comment]
Since we are on the topic, there is another type of message we show to the user in the output editor - a sleep message. It is meant to be used up until level 7 and should appear when the sleep command executes. However, it seems to be broken because the backend returns has_sleep as a boolean but the frontend expects it to be an array of integers. Should I create an issue for this or shall I throw it away?

**Comment by Felienne** [comment]
> Since we are on the topic, there is another type of message we show to the user in the output editor - a sleep message. It is meant to be used up until level 7 and should appear when the sleep command executes. However, it seems to be broken because the backend returns has_sleep as a boolean but the frontend expects it to be an array of integers. Should I create an issue for this or shall I throw it away?

I like the sleep message (it helps teacher see what is going on) so I would prefer to fix it but unlike the blocking issue it is not a priority
