### ISSUE TITLE
🪲Simon Says is broken

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#5983]
Annelies describes the problem here: https://github.com/hedyorg/hedy/issues/5266#issuecomment-2480582468

**Comment by boryanagoncharenko** [comment]
This is a bug I caused with introducing scopes in the lookup table. I am assigning it to myself.

**Comment by boryanagoncharenko** [comment]
I think I solved a different issue because I executed another snippet created by Annelies :\
Is this issue created for this error: `We detected that variable player_sequence is being used before being set. Can you set the variable before it is used or use quotation marks for player_sequence?`
generated by this snippet:
```
```
